#!/usr/bin/env python3

import requests
import argparse

proxies = {
  "http": "http://cache-etu.univ-artois.fr:3128",
  "https": "http://cache-etu.univ-artois.fr:3128",
}

parser = argparse.ArgumentParser(description="Displays the weather for a city")
parser.add_argument("city", type=str, help="City for which you want the weather")
args = parser.parse_args()

url = f"https://wttr.in/{args.city}?lang=fr"
r = requests.get(url)
r.encoding = "utf-8"
print(r.text)