#!/usr/bin/env python3

import re

texte = """
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789

aka aka kaa kaaaa


Caractères spéciaux
. [] {} () \ ^ $ | ? * +

https://rt-bethune.univ-artois.fr
http://toto.com

06 06 06 06 06
06 07 08 09 10
06/06/06/06/06
07.07.07.07 07
05-05-05-05-05

toto

11/11/11
11a123d
112112112
a11a11a11

Starsky_Hutch@zebra3.com
hugy@baycity.net
dobey_abc@123.gov

172.31.25.9

M. Robert Bruce
M.Rob
M Rob
Mme. Michel Germaine
"""

print("Tous les abc :")
motif = re.compile(r"abc")
matches = motif.finditer(texte)
for match in matches:
    print(match, match.span(), match.group(), sep="|")

print("Tous les abc qu'importe les majuscules et minuscules:")
motif = re.compile(r"[aA][bB][cC]")
matches = motif.finditer(texte)
for match in matches:
    print(match.group())

print("Tous les a répétés au moins deux fois")
print([match.group() for match in re.compile(r"aa+").finditer(texte)])

print("Les URL :")
# Tout ce qui démarre par http 
print([match.group() for match in re.compile(r"http.*").finditer(texte)])

print("4 entiers consécutifs")
print([match.group() for match in re.compile(r"\d{4}").finditer(texte)])

print("Possibles adresses IP :")
# un nombre de 1 à 3 chiffres suivi de 3 groupes composés 
# d'un point suivi d'un nombre de 1 à 3 chiffres 
print([match.group() for match in re.compile(r"\d{1,3}(\.\d{1,3}){3}").finditer(texte)])

print("Possibles numéros de téléphones :")
# Deux chiffres suivi de 4 fois un caractère quelconque suivi deux chiffres
print([match.group() for match in re.compile(r"\d\d(.\d\d){4}").finditer(texte)])

